# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kaydet.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import db

class kaydet(object):

    def kaydet(self):
        name = self.lineEdit.text()
        db.insert(name,movestring,tahtastring,sırasayısı,taraft,renkk)
        print("kaydedildi")

    def setupUi(self, Form ,sıra, sırasayı,süre,moveLog,tahta,taraf,renk):
        global taraft
        taraft = taraf
        global renkk
        renkk = renk
        self.sırasayı = sırasayı
        global sırasayısı
        sırasayısı = self.sırasayı
        self.tahta = tahta
        global tahtastring
        tahtastring = ""
        self.moveLog = moveLog
        self.sıra = sıra
        global globalsıra
        globalsıra = self.sıra
        self.süre =  süre
        global globalsüre
        globalsüre = self.süre
        global movestring
        movestring = ""
        for i in range(0,len(self.moveLog)):
            movestring = movestring +self.moveLog[i].getChessNotation() + "  " 
        for r in range(0,10):
            for c in range(0,10):
                tahtastring = tahtastring+self.tahta[r][c] + "  "
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(90, 180, 121, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.kaydet)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(90, 60, 121, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 60, 71, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(90, 120, 101, 31))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Kaydet"))
        self.label.setText(_translate("Form", "Oyun İsmi"))
        self.label_2.setText(_translate("Form", self.sıra))

    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = kaydet()
    ui.setupUi(Form,"a","a",0,0,0,0,0)
    Form.show()
    sys.exit(app.exec_())

def iukaydet(sıra,sırasayısı,süre,movelog,tahta,taraf,renk):
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = kaydet()
    ui.setupUi(Form,sıra,sırasayısı,süre,movelog,tahta,taraf,renk)
    Form.show()
    sys.exit(app.exec_())