# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kayıtlıOyunlar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import db,Oyun

class secondform(object):
    board = [   
            ["sK","sA","sY","sF","sV","sS","sF","sY","sA","sK"],
            ["sP","sP","sP","sP","sP","sP","sP","sP","sP","sP"],
            ["--","--","--","--","--","--","--","--","--","--"],
            ["--","--","--","--","--","--","--","--","--","--"],
            ["--","--","--","--","--","--","--","--","--","--"],
            ["--","--","--","--","--","--","--","--","--","--"],
            ["--","--","--","--","--","--","--","--","--","--"],
            ["--","--","--","--","--","--","--","--","--","--"],
            ["bP","bP","bP","bP","bP","bP","bP","bP","bP","bP"],
            ["bK","bA","bY","bF","bV","bS","bF","bY","bA","bK"]]
    moveLog = []
    def load(self):
        while self.tableWidget.rowCount() > 0:
            self.tableWidget.removeRow(0)
        result = db.show()
        self.tableWidget.insertRow(0)
        for row_number,row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number,data in enumerate(row_data):
                self.tableWidget.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(str(data)))
    def sil(self):
        result = db.show()
        for row in enumerate(result):
            if row[0]== self.tableWidget.currentRow():
                data = row[1]
                id = data[0]
                db.delete(id)
    def oynat(self):
        result = db.show()
        for row in enumerate(result):
            if row[0]== self.tableWidget.currentRow():    
                data = row[1]
                id = data[0]
                oyunismi = data[1]
                hamleler = data[2]
                tahtadüzeni = data[3]
                sırasayısı = data[4]
                taraf = data[5]
                renk = data[6]
                row = 0
                col = 0
                for i in range(0,398,2):
                    y = i+2
                    if tahtadüzeni[i:y] == "  ":
                        pass
                    else:
                        self.board[row][col] = tahtadüzeni[i:y]
                        if col <= 8:
                            col = col+1
                        elif col == 9:
                            row = row+1
                            col = 0
                Oyun.main(taraf,renk,1,self.board,sırasayısı)
                app.exit(app.exec())

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 500)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 400, 250))
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 280, 100, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.oynat)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 280, 100, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.sil)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 280, 100, 61))
        self.pushButton_3.setObjectName("pushButton_2")
        self.pushButton_3.clicked.connect(self.load)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Oyunu başlat"))
        self.pushButton_2.setText(_translate("Form", "Kayıtlı oyunu sil"))
        self.pushButton_3.setText(_translate("Form", "güncelle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = secondform()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

